name: CD

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build (prod)
        run: bash scripts/buildprod.sh
    
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: Build Image
        run: gcloud builds submit --tag europe-west4-docker.pkg.dev/notely-487814/notely-ar-repo/notely:latest

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
      - name: Run migrations
        run: ./scripts/migrateup.sh
      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-west4-docker.pkg.dev/notely-487814/notely-ar-repo/notely@sha256:23cd7de69612ea516026d446702137579f4eee26a46a7f818a7415b97bd0562b --region europe-west4 --allow-unauthenticated --project notely-487814 --max-instances=4
